name: all_star_learning
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.1+30

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cached_network_image: any
  in_app_update: ^4.2.2
  cupertino_icons:
  fluttertoast: ^8.2.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_screenutil: ^5.7.0
  flutter_widget_from_html: ^0.10.5+3
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  get_storage: ^2.1.1
  path_provider: ^2.1.4
  image_picker: ^0.8.7+1
  intl: any
  jwt_decoder: ^2.0.1
  logger: ^1.3.0
  marquee: ^2.2.3
  nepali_date_picker: ^5.3.1
  pretty_dio_logger: ^1.3.1
  searchable_paginated_dropdown: ^1.2.0
  syncfusion_flutter_calendar: ^30.1.39
  photo_view: ^0.14.0
  flutter_media_downloader: ^2.0.0
  external_path: ^2.2.0
  permission_handler: 11.4.0
  http_parser: ^4.0.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  awesome_notifications: ^0.10.1
  firebase_analytics: ^10.10.7
  syncfusion_flutter_pdfviewer: ^30.1.39
  device_info_plus: ^11.5.0
  flutter_bloc: ^8.1.6
  flutter_html: ^3.0.0-beta.2
  recase: ^4.1.0
  get_it: ^7.7.0
  dartz: ^0.10.1
  mobile_scanner: ^5.1.1
  youtube_player_flutter: ^9.1.1
  flutter_launcher_icons: ^0.14.4

  video_player: any
  nepali_utils: any
  url_launcher: ^6.3.0
  share_plus: ^10.0.0
  data_table_2: 2.5.10
dev_dependencies:
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/json/
    - assets/icons/
    - assets/icons/home/
    - assets/icons/drawer/
    - assets/icons/nav/
    - assets/icons/teacher_drawer/
    - assets/icons/teacherhome/
    - assets/icons/system/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"
  remove_alpha_ios: true
