// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXaG3v379CBQ2cHMnfWDhH4eZWryk_3U',
    appId: '1:396538585892:web:b90ca3eb86a241511f09b1',
    messagingSenderId: '396538585892',
    projectId: 'allstar-ems',
    authDomain: 'allstar-ems.firebaseapp.com',
    storageBucket: 'allstar-ems.appspot.com',
    measurementId: 'G-NHWGWJQ81V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gmciPDMKPfa4E1Htooqx6bWFoEKh8UE',
    appId: '1:396538585892:android:fe020826dd6036241f09b1',
    messagingSenderId: '396538585892',
    projectId: 'allstar-ems',
    storageBucket: 'allstar-ems.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtzep0Y0QxJ8F_GJFHvoXyYm_Upp1BGto',
    appId: '1:396538585892:ios:70fae4e613048c4d1f09b1',
    messagingSenderId: '396538585892',
    projectId: 'allstar-ems',
    storageBucket: 'allstar-ems.appspot.com',
    iosBundleId: 'com.example.allStarLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtzep0Y0QxJ8F_GJFHvoXyYm_Upp1BGto',
    appId: '1:396538585892:ios:70fae4e613048c4d1f09b1',
    messagingSenderId: '396538585892',
    projectId: 'allstar-ems',
    storageBucket: 'allstar-ems.appspot.com',
    iosBundleId: 'com.example.allStarLearning',
  );
}
